alog -sv2k17 -O2 -protect 0 -msg 5 -sve "$dsn/src/alu.v"
alog -sv2k17 -O2 -protect 0 -msg 5 -sve "$dsn/src/registerfile.v"
alog -sv2k17 -O2 -protect 0 -msg 5 -sve "$dsn/src/proccesor.v"
alog -sv2k17 -O2 -protect 0 -msg 5 -sve "$dsn/src/test.v"
alog -sv2k17 -O2 -protect 0 -msg 5 -sve "$dsn/src/cu.v"
alog -sv2k17 -O2 -protect 0 -msg 5 -sve "$dsn/src/decodeinst.v"
alog -sv2k17 -O2 -protect 0 -msg 5 -sve "$dsn/src/proccessoroperator.v"
alog -sv2k17 -O2 -protect 0 -msg 5 -sve "$dsn/src/datapath and controlunit.v"
